#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""German HTML Translator - Execute this file to translate all pages"""
import os, re, sys
BASE = os.path.dirname(os.path.abspath(__file__))
os.chdir(BASE)

def rf(p): 
    return open(p,'r',encoding='utf-8').read()
    
def wf(p, c): 
    os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p,'w',encoding='utf-8').write(c)

def t(h):
    h = h.replace('<html lang="en">','<html lang="de">')
    h = h.replace('Jannis Alexander Dietrich','Daniel Noah Dietrich')
    h = h.replace('Jannis Dietrich','Daniel Dietrich')
    h = h.replace('jannisdietrich.com','danieldietrich.tech')
    h = h.replace('&copy; 2026 Daniel Dietrich. All rights reserved','&copy; 2026 Daniel Dietrich. Alle Rechte vorbehalten')
    h = h.replace('aria-label="Back to top of page"','aria-label="Nach oben scrollen"')
    h = h.replace('>Back to top &uarr;<','>Nach oben &uarr;<')
    h = h.replace('> Terms <','> Nutzungsbedingungen <')
    h = h.replace('> Privacy <','> Datenschutz <')
    h = h.replace('> Source Code </a>','> Quellcode </a>')
    h = h.replace('> Live Demo </a>','> Live-Demo </a>')
    h = h.replace('>About</h2>','>Über mich</h2>')
    h = h.replace('>Education <svg','>Ausbildung <svg')
    h = h.replace('> Education </h2>','> Ausbildung </h2>')
    h = h.replace('>Education</h2>','>Ausbildung</h2>')
    h = h.replace('>Tech Stack / Skills</h2>','>Tech Stack / Fähigkeiten</h2>')
    h = h.replace('>Experience <svg','>Berufserfahrung <svg')
    h = h.replace('> Experience </h2>','> Berufserfahrung </h2>')
    h = h.replace('>Projects <svg','>Projekte <svg')
    h = h.replace('> Projects </h2>','> Projekte </h2>')
    h = h.replace('>Contact</h2>','>Kontakt</h2>')
    h = h.replace('> Projects <','> Projekte <')
    h = h.replace('> Work <','> Arbeit <')
    h = h.replace('<h2 id="features">Features</h2>','<h2 id="funktionen">Funktionen</h2>')
    h = h.replace('<h2 id="what-i-learned">What I Learned</h2>','<h2 id="was-ich-gelernt-habe">Was ich gelernt habe</h2>')
    h = h.replace('2 min read','2 Min. Lesen')
    h = h.replace('Built responsive web applications using React, Next.js, and TypeScript','Entwicklung responsiver Webanwendungen mit React, Next.js und TypeScript')
    h = h.replace('Developed cross-platform mobile apps with Flutter and Dart','Entwicklung plattformübergreifender mobiler Apps mit Flutter und Dart')
    h = h.replace('Integrated backends with Firebase, Supabase, and REST APIs','Integration von Backends mit Firebase, Supabase und REST-APIs')
    h = h.replace('Maintained clear communication with clients and delivered projects on time','Klare Kommunikation mit Kunden und pünktliche Projektlieferung')
    h = h.replace('Achieved top-rated status through consistent high-quality work','Top-Bewertung durch konstant hochwertige Arbeit erhalten')
    h = h.replace('Gained hands-on experience with AI/ML pipelines and natural language processing systems','Praktische Erfahrung mit KI/ML-Pipelines und Natural Language Processing')
    h = h.replace('Collaborated with cross-functional engineering teams in an agile environment','Zusammenarbeit mit interdisziplinären Entwicklungsteams in einem agilen Umfeld')
    h = h.replace('Assisted in testing and improving voice recognition features for in-car assistants','Mitarbeit beim Testen und Verbessern von Spracherkennungsfunktionen für Fahrzeugassistenten')
    h = h.replace('Developed internal tooling to streamline development workflows','Entwicklung interner Tools zur Optimierung von Entwicklungsabläufen')
    h = h.replace('Real-time shared lists synced via Firebase across all devices','Geteilte Listen in Echtzeit via Firebase über alle Geräte synchronisiert')
    h = h.replace('Offline-first architecture — works without internet','Offline-first-Architektur – funktioniert ohne Internet')
    h = h.replace('Published on both App Store and Google Play','Im App Store und bei Google Play veröffentlicht')
    h = h.replace('Interactive Three.js 3D phone mockup with React Three Fiber','Interaktives Three.js-3D-Telefon-Mockup mit React Three Fiber')
    h = h.replace('Scroll-triggered reveal animations and responsive design','Scroll-gesteuerte Einblend-Animationen und responsives Design')
    h = h.replace('Lazy-loaded 3D assets with optimized bundle size','Lazy-geladene 3D-Assets mit optimierter Bundle-Größe')
    h = h.replace('Spaced repetition algorithm for effective flashcard review','Spaced-Repetition-Algorithmus für effektives Karteikarten-Lernen')
    h = h.replace('Pomodoro timer with session statistics and streaks','Pomodoro-Timer mit Sitzungsstatistiken und Streaks')
    h = h.replace('Real-time sync via Supabase with offline fallback','Echtzeit-Synchronisierung via Supabase mit Offline-Fallback')
    h = h.replace('Live preview editor with multiple professional templates','Live-Vorschau-Editor mit mehreren professionellen Vorlagen')
    h = h.replace('AI-powered suggestions for improving resume bullet points','KI-gestützte Vorschläge zur Verbesserung von Lebenslauf-Stichpunkten')
    h = h.replace('High-quality PDF export with proper formatting','Hochqualitatives PDF-Export mit korrekter Formatierung')
    h = h.replace('Conversational AI with per-channel context memory','Konversations-KI mit kanalbasiertem Kontextgedächtnis')
    h = h.replace('Text-to-image generation from prompts','Text-zu-Bild-Generierung aus Eingaben')
    h = h.replace('Modular plugin architecture for adding new AI capabilities','Modulare Plugin-Architektur zum Hinzufügen neuer KI-Fähigkeiten')
    h = h.replace('XP-based leveling system with role rewards and leaderboards','XP-basiertes Leveling-System mit Rollen-Belohnungen und Bestenlisten')
    h = h.replace('Full moderation suite with audit logging','Vollständiges Moderations-Paket mit Audit-Logging')
    h = h.replace('Runs 24/7 on Linux VPS with automatic restarts','Läuft rund um die Uhr auf einem Linux-VPS mit automatischen Neustarts')
    h = h.replace('A cross-platform mobile app for collaborative grocery shopping with real-time sync, smart categories, and offline support. Published on iOS and Android.','Eine plattformübergreifende mobile App für gemeinsames Einkaufen mit Echtzeit-Synchronisierung, smarten Kategorien und Offline-Unterstützung. Verfügbar auf iOS und Android.')
    h = h.replace('A modern marketing website for the Shoply app featuring interactive 3D phone mockups, smooth scroll animations, and optimized performance.','Eine moderne Marketing-Website für die Shoply-App mit interaktiven 3D-Telefon-Mockups, sanften Scroll-Animationen und optimierter Performance.')
    h = h.replace('A mobile learning companion built with React Native and Expo — featuring spaced repetition flashcards, study planning, and progress tracking.','Ein mobiler Lernbegleiter mit React Native und Expo – mit Spaced-Repetition-Karteikarten, Lernplanung und Fortschrittsverfolgung.')
    h = h.replace('A web application that helps users create professional resumes with customizable templates, live preview editing, and AI-powered bullet point suggestions.','Eine Webanwendung, die Nutzern hilft, professionelle Lebensläufe mit anpassbaren Vorlagen, Live-Vorschau und KI-gestützten Verbesserungsvorschlägen zu erstellen.')
    h = h.replace('An AI-powered Discord bot bringing language models and image generation to servers — with context memory, rate limiting, and a modular plugin system.','Ein KI-gesteuerter Discord-Bot, der Sprachmodelle und Bildgenerierung in Server bringt – mit Kontextgedächtnis, Rate-Limiting und modularem Plugin-System.')
    h = h.replace('A feature-rich Discord bot for server management and entertainment — with moderation tools, XP leveling, music playback, and custom commands.','Ein funktionsreicher Discord-Bot für Server-Verwaltung und Unterhaltung – mit Moderations-Tools, XP-Leveling, Musikwiedergabe und benutzerdefinierten Befehlen.')
    bs = h.find('<body>')
    if bs > 0:
        hd = h[:bs]
        bd = h[bs:]
        for old, new in [('href="/legal/privacy/"','href="/de/legal/privacy/"'),('href="/legal/terms/"','href="/de/legal/terms/"'),('href="/projects/resumeme/"','href="/de/projects/resumeme/"'),('href="/projects/tharos-discord-bot/"','href="/de/projects/tharos-discord-bot/"'),('href="/projects/freeai-discord-bot/"','href="/de/projects/freeai-discord-bot/"'),('href="/projects/shoply-landing-page/"','href="/de/projects/shoply-landing-page/"'),('href="/projects/shoply-app/"','href="/de/projects/shoply-app/"'),('href="/projects/studyapp/"','href="/de/projects/studyapp/"'),('href="/projects/"','href="/de/projects/"'),('href="/work/"','href="/de/work/"')]:
            bd = bd.replace(old, new)
        h = hd + bd
    return h

def p(en, de, url):
    h = rf(en)
    h = t(h)
    h = re.sub(r'<link rel="canonical" href="[^"]*">', f'<link rel="canonical" href="{url}">', h)
    h = re.sub(r'<meta property="og:url" content="[^"]*">', f'<meta property="og:url" content="{url}">', h)
    h = re.sub(r'<meta name="twitter:url" content="[^"]*">', f'<meta name="twitter:url" content="{url}">', h)
    h = h.replace('content="en_US"><meta property="og:locale:alternate" content="de_DE"','content="de_DE"><meta property="og:locale:alternate" content="en_US"')
    wf(de, h)
    print(f'✓ {de}')

print('\n' + '='*70)
print('German HTML Translation')
print('='*70 + '\n')

p('index.html','de/index.html','https://danieldietrich.tech/de/')
p('work/index.html','de/work/index.html','https://danieldietrich.tech/de/work/')
p('projects/index.html','de/projects/index.html','https://danieldietrich.tech/de/projects/')
p('projects/resumeme/index.html','de/projects/resumeme/index.html','https://danieldietrich.tech/de/projects/resumeme/')
p('projects/tharos-discord-bot/index.html','de/projects/tharos-discord-bot/index.html','https://danieldietrich.tech/de/projects/tharos-discord-bot/')
p('projects/freeai-discord-bot/index.html','de/projects/freeai-discord-bot/index.html','https://danieldietrich.tech/de/projects/freeai-discord-bot/')
p('projects/shoply-landing-page/index.html','de/projects/shoply-landing-page/index.html','https://danieldietrich.tech/de/projects/shoply-landing-page/')
p('projects/shoply-app/index.html','de/projects/shoply-app/index.html','https://danieldietrich.tech/de/projects/shoply-app/')
p('projects/studyapp/index.html','de/projects/studyapp/index.html','https://danieldietrich.tech/de/projects/studyapp/')
p('legal/privacy/index.html','de/legal/privacy/index.html','https://danieldietrich.tech/de/legal/privacy/')
p('legal/terms/index.html','de/legal/terms/index.html','https://danieldietrich.tech/de/legal/terms/')

print('\n' + '='*70)
print('Translation Complete: 11/11 files')
print('='*70 + '\n')
